/*
 ================================================================================================
 Name        : mini_project4.c
 Author      : nada
 Description : Measure distance in cm using ultrasonic sensor
 Date        : 14/10/2022
 ================================================================================================
 */
#include<avr/io.h>/* To use the SREG register */
#include"lcd.h"
#include"ultrasonic_sensor.h"
#include"icu.h"

uint8 g_edgeCount =0;
uint16  g_timeHigh =0 ;

/* This is the call back function called by the ICU driver.
 *This is used to calculate the high time (pulse time) generated by
 *the ultrasonic sensor.*/

void Ultrasonic_edgeProcessing(void)
{ g_edgeCount++;

if(g_edgeCount == 1)
{
	/*
	 * Clear the timer counter register to start measurements from the
	 * first detected rising edge
	 */
	Icu_clearTimerValue();
	/* Detect falling edge */
	Icu_setEdgeDetectionType(FALLING);
}
else if(g_edgeCount == 2)
{
	/* Store the High time value */
	g_timeHigh = Icu_getInputCaptureValue();
	/* Detect rising edge */
	Icu_setEdgeDetectionType(RISING);
	/* Clear the timer counter register to start measurements again */
	Icu_clearTimerValue();
	/*   clear number of counts  */
		g_edgeCount=0;
}

}

int main(void)

{uint16 Distance =0;

/*enable i-bit*/
SREG|=(1<<7);

LCD_init(); /*intiallize the lcd*/
Ultrasonic_init(); /*intiallize the ultrasonic sensor*/

LCD_displayString("Distance =    cm");
while(1)
{
Distance= Ultrasonic_readDistance(); /*read distance*/

LCD_moveCursor(0,11);
if(Distance>=100)
{
	LCD_intgerToString(Distance);
}
else
{
	LCD_intgerToString(Distance);
	/*   In case the distance value is two or one digits print space in the next digit place    */
	LCD_displayCharacter(' ');
}


}
}




